spring:
  datasource:
    password:
    username: root
    url: jdbc:mysql://localhost:3306/one_chat?createDatabaseIfNotExist=true

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
